/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultWalletRouteImport } from './routes/result.$wallet'
import { Route as ApiPfpRouteImport } from './routes/api/pfp'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiBannerRouteImport } from './routes/api/banner'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultWalletRoute = ResultWalletRouteImport.update({
  id: '/result/$wallet',
  path: '/result/$wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPfpRoute = ApiPfpRouteImport.update({
  id: '/api/pfp',
  path: '/api/pfp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBannerRoute = ApiBannerRouteImport.update({
  id: '/api/banner',
  path: '/api/banner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/banner': typeof ApiBannerRoute
  '/api/og': typeof ApiOgRoute
  '/api/pfp': typeof ApiPfpRoute
  '/result/$wallet': typeof ResultWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/banner': typeof ApiBannerRoute
  '/api/og': typeof ApiOgRoute
  '/api/pfp': typeof ApiPfpRoute
  '/result/$wallet': typeof ResultWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/api/banner': typeof ApiBannerRoute
  '/api/og': typeof ApiOgRoute
  '/api/pfp': typeof ApiPfpRoute
  '/result/$wallet': typeof ResultWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/api/banner'
    | '/api/og'
    | '/api/pfp'
    | '/result/$wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/api/banner'
    | '/api/og'
    | '/api/pfp'
    | '/result/$wallet'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/api/banner'
    | '/api/og'
    | '/api/pfp'
    | '/result/$wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ApiBannerRoute: typeof ApiBannerRoute
  ApiOgRoute: typeof ApiOgRoute
  ApiPfpRoute: typeof ApiPfpRoute
  ResultWalletRoute: typeof ResultWalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$wallet': {
      id: '/result/$wallet'
      path: '/result/$wallet'
      fullPath: '/result/$wallet'
      preLoaderRoute: typeof ResultWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pfp': {
      id: '/api/pfp'
      path: '/api/pfp'
      fullPath: '/api/pfp'
      preLoaderRoute: typeof ApiPfpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/banner': {
      id: '/api/banner'
      path: '/api/banner'
      fullPath: '/api/banner'
      preLoaderRoute: typeof ApiBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  ApiBannerRoute: ApiBannerRoute,
  ApiOgRoute: ApiOgRoute,
  ApiPfpRoute: ApiPfpRoute,
  ResultWalletRoute: ResultWalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
